version: 2
updates:
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: daily
  allow:
    - dependency-type: "production"
    - dependency-type: "development"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - automerge
  versioning-strategy: increase
- package-ecosystem: 'github-actions'
  directory: '/'
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - automerge
