version: 2
updates:
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: daily
  allow:
    - dependency-type: "production"
  ignore:
    - dependency-name: "lodash.isarray"
      versions: ["4.x"]
    - dependency-name: "jquery"
      versions: [">= 1"]
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - automerge
  versioning-strategy: increase
- package-ecosystem: 'github-actions'
  directory: '/'
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - automerge
