name: Release

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Release
      shell: bash
      run: |
        docs/tools/git-config.sh
        export GIT_AUTHOR_DATE="$(git log -1 --format=%aD)"
        export GIT_COMMITTER_DATE="$(git log -1 --format=%cD)"
        
        # JRE Windows x86
        echo "jre-8u201-windows-i586.7z" >> .git/info/exclude
        wget -nv -O "jre-8u201-windows-i586.7z" https://archive.org/download/jre-8u201/jre-8u201-windows-i586.7z
        mkdir -p "bin/windows/x86/jre/jre-8u201-windows-i586"
        7z x -o"bin/windows/x86/jre/jre-8u201-windows-i586" "jre-8u201-windows-i586.7z" | grep "ing archive"
        rmdir "bin/windows/x86/jre/jre-8u201-windows-i586/jre1.8.0_201/lib/applet"
        git submodule add https://github.com/EIGHTFINITE/void "bin/windows/x86/jre/jre-8u201-windows-i586/jre1.8.0_201/lib/applet"
        git add ".gitmodules" "bin/windows/x86/jre/jre-8u201-windows-i586"
        git -c user.name="GitHub" -c user.email="noreply@github.com" commit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m"Add Windows x86 JRE 8u201 release artifacts" | sed -n 1p
        
        # JRE Windows x64
        echo "jre-8u201-windows-x64.7z" >> .git/info/exclude
        wget -nv -O "jre-8u201-windows-x64.7z" https://archive.org/download/jre-8u201/jre-8u201-windows-x64.7z
        mkdir -p "bin/windows/x64/jre/jre-8u201-windows-x64"
        7z x -o"bin/windows/x64/jre/jre-8u201-windows-x64" "jre-8u201-windows-x64.7z" | grep "ing archive"
        rmdir "bin/windows/x64/jre/jre-8u201-windows-x64/jre1.8.0_201/lib/applet"
        git submodule add https://github.com/EIGHTFINITE/void "bin/windows/x64/jre/jre-8u201-windows-x64/jre1.8.0_201/lib/applet"
        git add ".gitmodules" "bin/windows/x64/jre/jre-8u201-windows-x64"
        git -c user.name="GitHub" -c user.email="noreply@github.com" commit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m"Add Windows x64 JRE 8u201 release artifacts" | sed -n 1p
        
        # JRE Linux x64
        echo "jre-8u201-linux-x64.tar.gz" >> .git/info/exclude
        wget -nv -O "jre-8u201-linux-x64.tar.gz" https://archive.org/download/jre-8u201/jre-8u201-linux-x64.tar.gz
        mkdir -p "bin/linux/x64/jre/jre-8u201-linux-x64"
        tar -xzf "jre-8u201-linux-x64.tar.gz" -C "bin/linux/x64/jre/jre-8u201-linux-x64"
        rmdir "bin/linux/x64/jre/jre-8u201-linux-x64/jre1.8.0_201/lib/applet"
        git submodule add https://github.com/EIGHTFINITE/void "bin/linux/x64/jre/jre-8u201-linux-x64/jre1.8.0_201/lib/applet"
        git add ".gitmodules" "bin/linux/x64/jre/jre-8u201-linux-x64"
        git -c user.name="GitHub" -c user.email="noreply@github.com" commit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m"Add Linux x64 JRE 8u201 release artifacts" | sed -n 1p
        
        # 7z Windows x86
        echo "7z1900.exe" >> .git/info/exclude
        wget -nv -O "7z1900.exe" https://www.7-zip.org/a/7z1900.exe
        mkdir -p "bin/windows/x86/7z/7z1900"
        7z x -o"bin/windows/x86/7z/7z1900" "7z1900.exe" | grep "ing archive"
        rm "bin/windows/x86/7z/7z1900/Uninstall.exe"
        git add "bin/windows/x86/7z/7z1900"
        git -c user.name="GitHub" -c user.email="noreply@github.com" commit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m"Add Windows x86 7z 19.00 release artifacts" | sed -n 1p
        
        # 7z Windows x64
        echo "7z1900-x64.exe" >> .git/info/exclude
        wget -nv -O "7z1900-x64.exe" https://www.7-zip.org/a/7z1900-x64.exe
        mkdir -p "bin/windows/x64/7z/7z1900-x64"
        7z x -o"bin/windows/x64/7z/7z1900-x64" "7z1900-x64.exe" | grep "ing archive"
        rm "bin/windows/x64/7z/7z1900-x64/Uninstall.exe"
        git add "bin/windows/x64/7z/7z1900-x64"
        git -c user.name="GitHub" -c user.email="noreply@github.com" commit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m"Add Windows x64 7z 19.00 release artifacts" | sed -n 1p
        
        # Node Windows x86
        echo "node-v12.10.0-win-x86.zip" >> .git/info/exclude
        wget -nv -O "node-v12.10.0-win-x86.zip" https://nodejs.org/dist/v12.10.0/node-v12.10.0-win-x86.zip
        mkdir -p "bin/windows/x86/node"
        7z x -o"bin/windows/x86/node" "node-v12.10.0-win-x86.zip" | grep "ing archive"
        git add "bin/windows/x86/node"
        git -c user.name="GitHub" -c user.email="noreply@github.com" commit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m"Add Windows x86 Node 12.10.0 release artifacts" | sed -n 1p
        
        # Node Windows x64
        echo "node-v12.10.0-win-x64.zip" >> .git/info/exclude
        wget -nv -O "node-v12.10.0-win-x64.zip" https://nodejs.org/dist/v12.10.0/node-v12.10.0-win-x64.zip
        mkdir -p "bin/windows/x64/node"
        7z x -o"bin/windows/x64/node" "node-v12.10.0-win-x64.zip" | grep "ing archive"
        git add "bin/windows/x64/node"
        git -c user.name="GitHub" -c user.email="noreply@github.com" commit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m"Add Windows x64 Node 12.10.0 release artifacts" | sed -n 1p
        
        # Node Linux x64
        echo "node-v12.10.0-linux-x64.tar.xz" >> .git/info/exclude
        wget -nv -O "node-v12.10.0-linux-x64.tar.xz" https://nodejs.org/dist/v12.10.0/node-v12.10.0-linux-x64.tar.xz
        mkdir -p "bin/linux/x64/node"
        tar -xJf "node-v12.10.0-linux-x64.tar.xz" -C "bin/linux/x64/node"
        git add "bin/linux/x64/node"
        git -c user.name="GitHub" -c user.email="noreply@github.com" commit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m"Add Linux x64 Node 12.10.0 release artifacts" | sed -n 1p
        
        # Electron Windows x86
        export force_no_cache=true
        export npm_config_target=$(cat node_modules/electron/package.json | python -c "import sys, json; print json.load(sys.stdin)['version']")
        export npm_config_platform=win32
        export npm_config_arch=ia32
        bin/linux/x64/node/node-v12.10.0-linux-x64/bin/node node_modules/electron/install.js
        mkdir -p "bin/windows/x86/electron/electron-v$npm_config_target-win32-ia32"
        mv -T node_modules/electron/dist "bin/windows/x86/electron/electron-v$npm_config_target-win32-ia32"
        git add "bin/windows/x86/electron"
        git -c user.name="GitHub" -c user.email="noreply@github.com" commit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m"Add Windows x86 Electron $npm_config_target release artifacts" | sed -n 1p
        
        # Electron Windows x64
        export npm_config_arch=x64
        bin/linux/x64/node/node-v12.10.0-linux-x64/bin/node node_modules/electron/install.js
        mkdir -p "bin/windows/x64/electron/electron-v$npm_config_target-win32-ia32"
        mv -T node_modules/electron/dist "bin/windows/x64/electron/electron-v$npm_config_target-win32-x64"
        git add "bin/windows/x64/electron"
        git -c user.name="GitHub" -c user.email="noreply@github.com" commit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m"Add Windows x64 Electron $npm_config_target release artifacts" | sed -n 1p
        
        # Electron Linux x64
        export npm_config_platform=linux
        bin/linux/x64/node/node-v12.10.0-linux-x64/bin/node node_modules/electron/install.js
        mkdir -p "bin/linux/x64/electron/electron-v$npm_config_target-win32-ia32"
        mv -T node_modules/electron/dist "bin/linux/x64/electron/electron-v$npm_config_target-linux-x64"
        split -b 104857600 --numeric-suffixes=1 --suffix-length=3 "bin/linux/x64/electron/electron-v$npm_config_target-linux-x64/electron" "bin/linux/x64/electron/electron-v$npm_config_target-linux-x64/electron."
        echo "bin/linux/x64/electron/electron-v$npm_config_target-linux-x64/electron" > .git/info/exclude
        git add "bin/linux/x64/electron"
        git -c user.name="GitHub" -c user.email="noreply@github.com" commit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m"Add Linux x64 Electron $npm_config_target release artifacts" | sed -n 1p
        
        # Release
        git tag -f latest
        git push -f origin refs/tags/latest:refs/tags/latest
