name: "Hyperlinks"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 */8 * * *'

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: lycheeverse/lychee-action@v1.5.4
      with:
        args: '-m 20 -t 300 -m 0 --max-retries 0 --max-concurrency 1 --require-https -u "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" -- README.html'
