name: Hyperlinks

on:
  push:
  pull_request:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: lycheeverse/lychee-action@v1.0.9
      with:
        args: '-v -m 20 -t 300 --max-concurrency 1 --accept "403,429,503" --exclude "^[/-9@-Za-z_.-]+@[0-9a-z.-]+$" --user-agent "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko" --github-token "${{ secrets.GITHUB_TOKEN }}" -- README.html'
