name: Hyperlinks

on:
  push:
  pull_request:
  schedule:
    - cron: '0 */6 * * *'

env:
  CI: true

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: peter-evans/link-checker@master
      with:
        args: '-c 1 -r -t 300 -v README.html'
      env:
        LINKCHECKER_OUTPUT_DIR: '.'
        LINKCHECKER_OUTPUT_FILENAME: 'link-checker-out.txt'
    - name: Hyperlinks
      shell: bash
      run: |
        if [[ -f "link-checker-out.txt" && $(cat link-checker-out.txt | grep -P '^(\tERROR|\t\t)' | tee /dev/stderr | sed '$!N;s/\n//' | sed -E '/^\tERROR\thttps:\/\/(www\.curseforge\.com\/.*\t\tForbidden \(HTTP error 403\)|www\.minecraftforum\.net\/.*\t\tService Unavailable \(HTTP error 503\)|www\.npmjs\.com\/.*\t\t(Too Many Requests \(HTTP error 429\)|Internal Server Error \(HTTP error 500\))|github\.com\/.*\t\tToo Many Requests \(HTTP error 429\)|(archive|(commons|hc)\.apache)\.org\/.*\t\tDialing to the given TCP address timed out|web\.archive\.org\/.*\t\t(Bad Gateway \(HTTP error 502\)|Service Unavailable \(HTTP error 503\)|Gateway Timeout \(HTTP error 504\)))$/d' | head -c1 | wc -c) -ne 0 ]]
          then exit 1
        fi
