name: Check Links

on:
  push:
  pull_request:
  schedule:
    - cron: '0 */6 * * *'

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: peter-evans/link-checker@master
      with:
        args: '-c 1 -r -t 300 -v README.html'
      env:
        LINKCHECKER_OUTPUT_DIR: '.'
        LINKCHECKER_OUTPUT_FILENAME: 'link-checker-out.txt'
    - name: Result
      shell: bash
      run: |
        if [[ $(cat link-checker-out.txt | grep -P '^(\tERROR|\t\t)' | tee /dev/stderr | head -c1 | wc -c) -ne 0 ]]
          then exit 1
        fi
