name: Check Links

on:
  push:
  pull_request:
  schedule:
    - cron: '0 */6 * * *'

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: peter-evans/link-checker@master
      with:
        args: '-c 1 -r -t 300 -v README.html'
      env:
        LINKCHECKER_OUTPUT_DIR: '.'
        LINKCHECKER_OUTPUT_FILENAME: 'link-checker-out.txt'
    - name: Result
      shell: bash
      run: |
        if [[ -f "link-checker-out.txt" && $(cat link-checker-out.txt | grep -P '^(\tERROR|\t\t)' | sed '$!N;s/\n//' | sed -E '/^\tERROR\thttps:\/\/((github|www\.npmjs)\.com\/.*?\t\tToo Many Requests \(HTTP error 429\)|www\.curseforge\.com\/.*?\t\tForbidden \(HTTP error 403\)|www\.minecraftforum\.net\/.*?\t\tService Unavailable \(HTTP error 503\))$/d' | tee /dev/stderr | head -c1 | wc -c) -ne 0 ]]
          then exit 1
        fi
