name: README

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

env:
  CI: true

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: latest
        path: bin
    - uses: actions/checkout@master
      with:
        path: EIGHTFINITE-build
    - name: README
      shell: bash
      run: |
        mkdir -p "EIGHTFINITE-build/bin"
        mv -T bin/bin "EIGHTFINITE-build/bin"
        mkdir -p "EIGHTFINITE-build/node_modules"
        mv -T bin/node_modules "EIGHTFINITE-build/node_modules"
        mv -T bin/package-lock.json "EIGHTFINITE-build/package-lock.json"
        rm -r bin/
        cd EIGHTFINITE-build
        docs/tools/git-config.sh
        bin/linux/x64/node/node-v12.10.0-linux-x64/bin/node --use_strict main.js --readme_only
        cd ..
    - uses: peter-evans/create-pull-request@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: EIGHTFINITE-build
        commit-message: Update README
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        committer: GitHub <noreply@github.com>
        title: Update the README
        body: |
          Update the README.
        labels: auto-merge
        branch: actions/readme
        base: master
